config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  # get 'products/new'
  # get 'products/:id', to: 'products#show', as: 'product'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates(:name, presence: true)
  validates(:price, presence: true, numericality: { less_than: 100000})
  validates(:manufacturer, presence: true)


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(id: :asc)
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def edit
    @product = Product.find(params[:id])
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to root_url
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def product_params
    params.require(:product).permit(:name, :price, :manufacturer, :released)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
  <title>製品管理</title>
  <%= stylesheet_link_tag 'application' %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/products/edit.html.erb
<h1>製品情報の編集</h1>
<table>
  <%= form_for(@product) do |f| %>
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :price %></th>
        <td><%= f.text_field :price %></td>
      </tr>
      <tr>
        <th><%= f.label :manufacturer %></th>
        <td><%= f.text_field :manufacturer %></td>
      </tr>
      <tr>
        <th></th>
        <td>
          <%= f.check_box :released %>
          <%= f.label :released %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= f.submit '保存' %>
        </td>
      </tr>
  <% end %>
</table>

app/views/products/index.html.erb
<h1>製品一覧</h1>
<table>
  <tr>
    <th>名称</th>
    <th></th>
    <th></th>
  </tr>
  <% @products.each do |p| -%>
      <tr>
        <td><%= h p.name %></td>
        <td><%= link_to '詳細', product_path(p.id)  %></td>
        <td><%= button_to 'delete', product_path(p.id), method: :delete, data: {confirm: "You sure?"} %></td>
      </tr>
  <% end %>
  <p><%= link_to 'add new',new_product_path %></p>
</table>

app/views/products/new.html.erb
<h1>製品の追加</h1>
<h1><%=t :hello %></h1>
<%=t :hello  %>

<%= render 'shared/error_messages' %>
<table>
  <%= form_for(@product) do |f| %>
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :price %></th>
        <td><%= f.text_field :price %></td>
      </tr>
      <tr>
        <th><%= f.label :manufacturer %></th>
        <td><%= f.text_field :manufacturer %></td>
      </tr>
      <tr>
        <th></th>
        <td>
          <%= f.check_box :released %>
          <%= f.label :released %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <%= f.submit 'add' %>
        </td>
      </tr>
  <% end %>
</table>

app/views/products/show.html.erb
<h1>
  製品の詳細情報
</h1>
<table>
  <tr>
    <th>名状</th>
    <td><%= h @product.name %></td>
  </tr>
  <tr>
    <th>価格</th>
    <td>&yen;<%= number_with_delimiter(@product.price) %></td>
  </tr>
  <tr>
    <th>製造者</th>
    <td><%= h @product.manufacturer %></td>
  </tr>
  <tr>
    <th>販売開始</th>
    <td><%= @product.released? ? '○' : '×' %></td>
  </tr>
</table>

<%= link_to "edit", edit_product_path, method: :edit %>

app/views/shared/_error_messages.html.erb
<% if @product.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@product.errors.count, "error") %>.
      </div>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>